export const metadata = {
  title: "ChitChat",
  description: "Generated by create next app",
};

export default function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
