import { Sidebar } from "./components";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="md:grid grid-cols-[auto_1fr] relative ">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
