import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "../components/ThemeProvider";
import "./globals.css";
import { Providers } from "../redux/Providers";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <Suspense fallback={<Loading />}>
              <Sidebar>{children}</Sidebar>
            </Suspense>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
