export const metadata = {
  title: "ChitChat",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="fixed inset-0 bg-white">{children}</main>;
}
